---
title: "Figure 1 - basic QC"
author: "Kimberly Olney, PhD"
date: "04/19/2024"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = ".", echo=TRUE, warning=FALSE, message=FALSE)
```

# Libraris, paths, colors
https://satijalab.org/seurat/articles/essential_commands.html 
```{r echo=FALSE, message=FALSE}
#source(here::here("/research/labs/neurology/fryer/m239830/PMI/scripts", "file_paths_and_colours.R"))
source(here::here("scripts/", "file_paths_and_colours.R"))
getwd()

treatment <- "PMI"
group_colors <- c("lightblue", "#bebada", "#377eb8", "#984ea3")
sample_colors <- c("lightblue","lightblue","lightblue","lightblue","#bebada","#bebada","#bebada","#bebada", "#377eb8",  "#377eb8",  "#377eb8",  "#377eb8",  "#377eb8", "#984ea3", "#984ea3", "#984ea3", "#984ea3", "#984ea3")

color.panel <- dittoColors()
library(ggpubr)
```

# Read in object
```{r read_object}
# read object
dataObject <- readRDS(file = paste0("../rObjects/",treatment,".dataObject.clean.rds"))
# inspect
dataObject$sample <- factor(dataObject$sample, levels = c("J_3", "J_4", "B_7", "P_65", "P_52", "P_62", "P_67", "P_69", "B_10", "B_8", "B_9", "J_1", "J_2", "P_53", "P_54", "P_64", "P_68", "P_71"))
```

# QC violins 
```{r violin}
# nFeature, nCount, and cell.complexity violins
VlnPlot(dataObject,
              features = c( "nCount_RNA","nFeature_RNA", "cell.complexity", "percent.mt"),
              ncol = 4,
              group.by = 'group_no_sex',
              cols = group_colors,
              pt.size = 0)  

# Generate individual violin plots
plots <- lapply(c("nCount_RNA", "nFeature_RNA", "cell.complexity", "percent.mt"), function(feature) {
  VlnPlot(dataObject, features = feature, group.by = 'group_no_sex', pt.size = 0) + 
    theme(axis.text = element_text(size = 10),
          axis.title = element_text(size = 10),
          axis.title.x = element_blank(),
          plot.title = element_text(size = 10, face = "plain"),
          legend.position = "none") +
    scale_fill_manual(values = group_colors)

})

# Combine the individual plots into a single plot
v1 <- CombinePlots(plots, ncol = 4)





# Generate individual violin plots
plots <- lapply(c("nCount_RNA", "nFeature_RNA", "cell.complexity", "percent.mt"), function(feature) {
  VlnPlot(dataObject, features = feature, group.by = 'sample', pt.size = 0) + 
    theme(axis.text = element_text(size = 10),
          axis.title = element_text(size = 10),
          axis.title.x = element_blank(),
          plot.title = element_text(size = 10, face = "plain"),
          legend.position = "none") +
    scale_fill_manual(values = sample_colors)

})

# Combine the individual plots into a single plot
v2 <- CombinePlots(plots, nrow = 4)

```

# Nuclei count per sample and/or per group
```{r number_cells2}
# Visualize the number of cell counts per sample
data <- as.data.frame(table(dataObject$sample, dataObject$group_no_sex))
data2 <- subset(data, Freq > 0)
data_sample <- as.data.frame(table(dataObject$sample))

colnames(data2) <- c("sample", "group","frequency")
colnames(data_sample) <- c("sample","frequency")

data2$sample <- factor(data2$sample, levels = data2$sample)
nuclei_count <- ggplot(data2, aes(x = sample, y = frequency, fill = group)) + 
  geom_col() +
  theme_classic() +
#  geom_text(aes(label = frequency), 
 #           position=position_dodge(width=0.9), 
 #           vjust=-0.25, size = 3) +
  scale_y_continuous(breaks = seq(0,10000, by = 2000), limits = c(0,10000)) +
  ggtitle("Nuclei count") +
    theme(axis.text = element_blank(),
          axis.title = element_text(size = 10),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          plot.title = element_text(size = 10),
          legend.position = "none")
nuclei_count


# Create the plot
nuclei_count_plot <- ggplot(data2, aes(x = sample, y = frequency, fill = group)) + 
  geom_col() +
  theme_classic() +
  scale_y_continuous(breaks = seq(0, 10000, by = 2000), limits = c(0, 10000)) +
  facet_wrap(~ group, scales = "free_x", nrow = 1, strip.position = "bottom") +  # Arrange plots in a single row, group label at bottom
  ggtitle("              Nuclei count by sample") +
  theme(axis.text = element_text(size = 10),
        axis.text.x = element_blank(),
       # axis.title.x = element_text(size = 10),
        axis.title = element_text(size = 10),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 10),
        strip.background = element_blank(),
        strip.placement = "outside",  # Place group labels outside the x-axis
        plot.title.position = "plot",
        legend.position = "none") +
  scale_fill_manual(values = group_colors)

# Display the plot
nuclei_count_plot
```

# ANOVA 
```{r ANOVA}
data2 <- read.delim("../meta.txt")
# Load necessary libraries
library(ggplot2)
library(car)  # For Levene's Test

# Check Assumptions
data2$PMI.in.hours <- as.factor(data2$PMI.in.hours)
# 1. Shapiro-Wilk test for normality of nuclei count by group
# Fit a linear model
anova_model <- aov(RIN ~ PMI.in.hours, data = data2)
t.test(RIN ~ PMI.in.hours, data = data2, var.equal = TRUE)
help(t.test)
# Extract residuals
residuals <- residuals(anova_model)

# Shapiro-Wilk test on residuals
shapiro_test <- shapiro.test(residuals)
print(shapiro_test)

# 2. Levene's Test for homogeneity of variances
levene_test <- leveneTest(RIN ~ PMI.in.hours, data = data2)
print(levene_test)

# Run the ANOVA
anova_result <- summary(anova_model)
print(anova_result)

# Post-hoc Analysis (if ANOVA is significant)
if (anova_result[[1]][["Pr(>F)"]][1] < 0.05) {
  tukey_result <- TukeyHSD(anova_model)
  print(tukey_result)
}
# Fit the ANOVA model
anova_model <- aov(frequency ~ group, data = data2)

# Get confidence intervals for the group means
conf_intervals <- confint(anova_model)
print(conf_intervals)
```

# Cell cycle
```{r cellcycle}
dataObject <- CellCycleScoring(dataObject, 
                                        s.features = m.s.genes$gene_name, 
                                        g2m.features = m.g2m.genes$gene_name, 
                                        set.ident = TRUE)

Idents(dataObject)
dataObject
# sample before integration 
cellcyle <- dataObject@meta.data %>%
  group_by(group_no_sex, Phase) %>% 
  dplyr::count() %>%
  group_by(group_no_sex) %>%
  dplyr::mutate(percent = 100*n/sum(n)) %>%
  ungroup()  %>%
  ggplot(aes(x=group_no_sex,y=percent, fill=Phase)) +
  geom_col() +
  ggtitle("Percentage of cell cycle phase") +
  theme_classic() + 
      theme(axis.text.x = element_text(size = 10),
          axis.text = element_text(size = 10),
          axis.title = element_text(size = 10),
          axis.title.x = element_text(size = 10),
          plot.title = element_text(size = 10),
          legend.margin = margin(0, 0, 0, -.5, unit = "cm"),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          legend.key.size = unit(0.5, "cm")) +
  scale_fill_manual(values = c("gray", "navy", "gold3"))
cellcyle


# cellcyle <- dataObject@meta.data %>%
#   group_by(group_no_sex, Phase) %>% 
#   dplyr::count() %>%
#   group_by(group_no_sex) %>%
#   dplyr::mutate(percent = 100*n/sum(n)) %>%
#   ungroup() 
# 
# # Reshape the data to a contingency table
# contingency_table <- cellcyle %>%
#   select(group_no_sex, Phase, percent) %>%
#   pivot_wider(names_from = group_no_sex, values_from = percent, values_fill = list(percent = 0))
# rownames(contingency_table) <- contingency_table$Phase
# contingency_table <- contingency_table %>%
#   select(-Phase)
# contingency_matrix <- as.matrix(contingency_table)
# print(contingency_matrix)
# 
# # Perform the Chi-Square Test of Independence
# chi_square_result <- chisq.test(contingency_matrix)
# print(chi_square_result)
```

# UMAP 
```{r}
cell_types <- c("neuron", "interneuron", "astrocyte", "oligodendrocyte", "fibroblast", "polydendrocyte", "endothelial", "mural", "microglia")
dataObject$individual_clusters <- factor(dataObject$individual_clusters, levels = cell_types)

library(ggrepel)

ditto_umap <- dittoDimPlot(object = dataObject,
            size = .0001, 
             var = "individual_clusters",
             dim.1 = 1, 
             dim.2 = 2,
             reduction.use = "umap",
             legend.size = 2,
             do.label = FALSE,
             legend.show = TRUE,
             labels.highlight = TRUE,
             labels.repel = TRUE,  # Enable ggrepel to move labels away from clusters
             main = "UMAP")  # Add the title

# Display the plot
ditto_umap

library(ggplot2)
library(dittoSeq)

# Create the UMAP plot
p <- dittoDimPlot(
  object = dataObject,
  var = "individual_clusters",
  size = .0001, 
  dim.1 = 1, 
  dim.2 = 2,
  reduction.use = "umap",
  legend.size = 2,
  do.label = FALSE,
  legend.show = TRUE,
  labels.highlight = TRUE,
  labels.repel = TRUE,  # Enable ggrepel to move labels away from clusters
  main = "UMAP"
)

# Adjust the legend
umap <- p + theme(
  legend.position = "right",  # Move the legend closer
  legend.box.margin = margin(0, 0, 0, -5),  # Remove extra margin around the legend
  legend.spacing = unit(0.1, "cm"),  # Reduce space between legend keys
  legend.key.size = unit(0.4, "cm"),  # Adjust the size of the legend keys
  legend.margin = margin(0, 0, 0, -.1, unit = "cm"),
  plot.title = element_text(size = 10)

)

baseplot <- DimPlot(dataObject, reduction = "umap")
baseplot
```

# Cell type count 
```{r}
Idents(dataObject) <- dataObject$individual_clusters
cell_types <- unique(Idents(dataObject))

count_per_cluster <- FetchData(dataObject,
                               vars = c("ident", "orig.ident")) %>%
  dplyr::count(ident, orig.ident) %>%
  tidyr::spread(ident, n)
count_per_cluster

count_melt <- reshape2::melt(count_per_cluster)
colnames(count_melt) <- c("ident", "cluster", "number of nuclei")
count_max <- count_melt[which.max(count_melt$`number of nuclei`), ]
count_max_value <- count_max$`number of nuclei`
cellmax <- count_max_value + 10500 # so that the figure doesn't cut off the text
count_bar <- ggplot(count_melt, aes(x = factor(cluster), y = `number of nuclei`, fill = `cluster`)) +
  geom_bar(
    stat = "identity",
    colour = "black",
    width = 1,
    position = position_dodge(width = 0.8)
  ) +
  geom_text(
    aes(label = `number of nuclei`),
    position = position_dodge(width = 0.9),
    vjust = -0.25,
    angle = 45,
    hjust = -.01, 
    size = 3
  ) +
  theme_classic() + scale_fill_manual(values = color.panel) +
  ggtitle("Number of nuclei per cluster") +  xlab("cluster") +
      theme(axis.text = element_text(size = 10),
          axis.title = element_text(size = 10),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.x = element_text(size = 10, angle = 45, hjust = 1), 
          plot.title = element_text(size = 10),
          legend.position = "none") +
  scale_y_continuous(limits = c(0, cellmax))
count_bar
```


# Count per cluster
```{r}
# Fetch data including time point
count_per_cluster <- FetchData(dataObject,
                               vars = c("ident", "orig.ident", "time")) %>%
  dplyr::count(ident, orig.ident, time) %>%
  tidyr::spread(ident, n)

# Reshape the data for plotting
count_melt <- reshape2::melt(count_per_cluster, id.vars = c("orig.ident", "time"))
colnames(count_melt) <- c("orig.ident", "time", "cluster", "number_of_nuclei")

# Find the maximum number of nuclei for plot scaling
count_max <- count_melt[which.max(count_melt$number_of_nuclei), ]
count_max_value <- count_max$number_of_nuclei
cellmax <- count_max_value + 2500 # Adjust plot limits

# Create the bar plot
count_bar_time <- ggplot(count_melt, aes(x = factor(cluster), y = number_of_nuclei, fill = time)) +
  geom_bar(
    stat = "identity",
    colour = "black",
    width = 0.7,
    position = position_dodge(width = 0.8)
  ) +
#  geom_text(
#    aes(label = number_of_nuclei),
#    position = position_dodge(width = 0.8),
#    vjust = -0.5,
#    angle = 75,
#    hjust = -.1
#  ) +
  theme_classic() +
  scale_fill_manual(values = c("0" = "lightblue", "3" = "gray20")) + # Adjust colors as needed
  ggtitle("Number of nuclei per cell type by time point") +
  xlab("Cluster") +
  ylab("Number of Nuclei") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(breaks = seq(0,25000, by = 5000), limits = c(0, cellmax))
count_bar_time
```


# Combine all plots 
```{r}

row1 <- ggarrange(
  NULL,
  ncol = 1,
  labels = c("A"), 
  font.label = list(size = 10)
)
# row 1 experimental set up 
row2 <- ggarrange(
  v1,
  ncol = 1,
  labels = c("B"), 
  font.label = list(size = 10)
)

row3 <- ggarrange(
  nuclei_count_plot,
  cellcyle,
  ncol = 2,
  labels = c("B","C"), 
  widths = c(1.5, 1), 
  font.label = list(size = 10)
)

row4 <- ggarrange(
  umap,
 # count_bar,
  labels = c("D"), 
 # widths = c(1.5, 1), 
  font.label = list(size = 10)
  )

combind <-
  ggarrange(
    row1,
   # row2,
    row3,
    NULL,
    row4,
    nrow = 4,
    heights = c(1,1,.1,1.75)
    )
combind

path <- paste0("../manuscript_figures/Figure_1_small_UMAP_v2")
saveToPDF(paste0(path, ".pdf"), width = 7.5, height = 9)

#umap
#path <- paste0("../manuscript_figures/small_UMAP")
#saveToPDF(paste0(path, ".pdf"), width = 7.5, height = 7)

combind <-
  ggarrange(
    v1,
    v2,
    nrow = 2,
    heights = c(1,4)
    )
combind
path <- paste0("../manuscript_figures/Supplemental_QC")
saveToPDF(paste0(path, ".pdf"), width = 7.5, height = 9)
```


