---
title: "Figure 2 - 3-hour versus 0-hour differential expression"
author: "Kimberly Olney, PhD"
date: "07/24/2024"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = ".", echo=TRUE, warning=FALSE, message=FALSE)
library("readxl")
library(forcats)
library(ggpubr)
```

# Libraris, paths, colors
https://satijalab.org/seurat/articles/essential_commands.html 
```{r echo=FALSE, message=FALSE}
source(here::here("/research/labs/neurology/fryer/m239830/PMI/scripts", "file_paths_and_colours.R"))
treatment <- "PMI"
```

# Volcano 
```{r params}
qval = 0.1
posFC = 0 
negFC = 0 
FC = 0
```

## Neuron: 3 versus 0 hours
```{r volcano_neuron, warning=FALSE}
i <- "neuron"
  ind1_vs_ind2 <- read.delim(paste0("../results/DEGs/DESeq2_pseudobulk_exp_filter/", i, "_3_vs_0_hours_comparison_pseudobulk.txt"))
  ind1_vs_ind2 <- na.omit(ind1_vs_ind2)

sig <- subset(ind1_vs_ind2, padj < 0.1)
up <- subset(sig, log2FoldChange > 0)
down <- subset(sig, log2FoldChange < 0)

    color_values <- vector()
max <- nrow(ind1_vs_ind2)
  for (row in 1:max) {
    if (!is.na(ind1_vs_ind2$padj[row])) {  # Check for NA values in padj
      if (ind1_vs_ind2$padj[row] < qval) {
        if (ind1_vs_ind2$log2FoldChange[row] > posFC) {
          color_values <- c(color_values, 1)
        } else if (ind1_vs_ind2$log2FoldChange[row] < negFC) {
          color_values <- c(color_values, 2)
        } else {
          color_values <- c(color_values, 3)
        }
      } else {
        color_values <- c(color_values, 3)
      }
    } else {
      color_values <- c(color_values, 3)  # Handle NA values in padj
    }
  }
  ind1_vs_ind2$color_adjpval_0.05 <- factor(color_values)
    data <- ind1_vs_ind2
    up <- data[data$color_adjpval_0.05 == 1,]
    up <- up[!grepl("ENSG", up$gene),]
    up10 <- up[1:15,]
    upFold <- subset(up, log2FoldChange > 1)
    upFold <- upFold[!(upFold$gene %in% up10$gene),]
    upFold <- upFold[1:10,]

    down <- data[data$color_adjpval_0.05 == 2,]
    down <- down[!grepl("ENSG", down$gene),]
    down10 <- down[1:10,]
    downFold <- subset(down, log2FoldChange < -2)
    downFold <- downFold[!(downFold$gene %in% down10$gene),]
    downFold <- downFold[1:10,]

    if (!1 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c(  "darkgreen","gray")
      } else if (!2 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c( "purple","gray")
      } else if (!1 %in% unique(data$color_adjpval_0.05) && !2 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c("gray")
      } else {
        my_colors <- c( "purple",   "darkgreen","gray")
      }
      # plot
      hadjpval <- (-log10(max(data$pvalue[data$padj < qval], na.rm=TRUE)))

neuron_vol <- ggplot(data = data, aes(x = log2FoldChange,y = -log10(pvalue), color = color_adjpval_0.05)) + 
        geom_point(alpha = 0.8, size = 1) +  
        theme_bw() +  
        theme(legend.position = "none") + 
        scale_color_manual(values = my_colors) + 
        labs(x = expression(log[2](FC)), 
          y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)") ) +
        theme(legend.position = "none",
              plot.title = element_text(size = 10, margin = margin(0,0,0.3,0)),
              axis.title.x = element_text(size = 10),
              axis.text.x = element_text(size = 10),
              axis.title.y = element_text(size = 10),
              axis.text.y = element_text(size = 10)) +
      geom_hline(yintercept = hadjpval,
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle(paste0(i, "\n3-hour versus 0-hour \nq-value < ", qval)) +
  scale_x_continuous(limits = c(-3, 3), breaks = seq(-3, 3, 1)) +
  scale_y_continuous(limits = c(0, 20), breaks = seq(0, 20, 5)) +
      geom_text_repel(
        data = up,
        aes(
          x = log2FoldChange,
          y = -log10(pvalue),
          label = gene
        ),
        nudge_x = 0.1,
        color = "purple",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 8)
      ) +
      geom_text_repel(
        data = down,
        aes(
          x = log2FoldChange,
          y = -log10(pvalue),
          label = gene
        ),
        nudge_x = -0.1,
        color = "darkgreen",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 8)
      ) 
neuron_vol
rm(up10, upFold, up, down, down10, downFold)
```

## Interneuron: 3 versus 0 hours
```{r volcano_interneuron, warning=FALSE}
i <- "interneuron"
  ind1_vs_ind2 <- read.delim(paste0("../results/DEGs/DESeq2_pseudobulk_exp_filter/", i, "_3_vs_0_hours_comparison_pseudobulk.txt"))
  ind1_vs_ind2 <- na.omit(ind1_vs_ind2)

sig <- subset(ind1_vs_ind2, padj < 0.1)
up <- subset(sig, log2FoldChange > 0)
down <- subset(sig, log2FoldChange < 0)

    color_values <- vector()
max <- nrow(ind1_vs_ind2)
  for (row in 1:max) {
    if (!is.na(ind1_vs_ind2$padj[row])) {  # Check for NA values in padj
      if (ind1_vs_ind2$padj[row] < qval) {
        if (ind1_vs_ind2$log2FoldChange[row] > posFC) {
          color_values <- c(color_values, 1)
        } else if (ind1_vs_ind2$log2FoldChange[row] < negFC) {
          color_values <- c(color_values, 2)
        } else {
          color_values <- c(color_values, 3)
        }
      } else {
        color_values <- c(color_values, 3)
      }
    } else {
      color_values <- c(color_values, 3)  # Handle NA values in padj
    }
  }
  ind1_vs_ind2$color_adjpval_0.05 <- factor(color_values)
    data <- ind1_vs_ind2
    up <- data[data$color_adjpval_0.05 == 1,]
    up <- up[!grepl("ENSG", up$gene),]
    up10 <- up[1:10,]
    upFold <- subset(up, log2FoldChange > 2)
    upFold <- upFold[!(upFold$gene %in% up10$gene),]
    upFold <- upFold[1:10,]

    down <- data[data$color_adjpval_0.05 == 2,]
    down <- down[!grepl("ENSG", down$gene),]
    down10 <- down[1:10,]
    downFold <- subset(down, log2FoldChange < -2)
    downFold <- downFold[!(downFold$gene %in% down10$gene),]
    downFold <- downFold[1:10,]

    if (!1 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c(   "darkgreen","gray")
      } else if (!2 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c( "purple","gray")
      } else if (!1 %in% unique(data$color_adjpval_0.05) && !2 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c("gray")
      } else {
        my_colors <- c( "purple",   "darkgreen","gray")
      }
      # plot
      hadjpval <- (-log10(max(data$pvalue[data$padj < qval], na.rm=TRUE)))

interneuron_vol <- ggplot(data = data, aes(x = log2FoldChange,y = -log10(pvalue), color = color_adjpval_0.05)) + 
        geom_point(alpha = 0.8, size = 1) +  
        theme_bw() +  
        theme(legend.position = "none") + 
        scale_color_manual(values = my_colors) + 
        labs(x = expression(log[2](FC)), 
          y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)") ) +
        theme(legend.position = "none",
              plot.title = element_text(size = 10, margin = margin(0,0,0.3,0)),
              axis.title.x = element_text(size = 10),
              axis.text.x = element_text(size = 10),
              axis.title.y = element_text(size = 10),
              axis.text.y = element_text(size = 10)) +
      geom_hline(yintercept = hadjpval,
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle(paste0(i, "\n3-hour versus 0-hour \nq-value < ", qval)) +
  scale_x_continuous(limits = c(-3, 3), breaks = seq(-3, 3, 1)) +
  scale_y_continuous(limits = c(0, 20), breaks = seq(0, 20, 5)) +
      geom_text_repel(
        data = up,
        aes(
          x = log2FoldChange,
          y = -log10(pvalue),
          label = gene
        ),
        nudge_x = 0.1,
        color = "purple",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 20)
      ) +
      geom_text_repel(
        data = down,
        aes(
          x = log2FoldChange,
          y = -log10(pvalue),
          label = gene
        ),
        nudge_x = -0.2,
        color = "darkgreen",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 10)
      ) 
interneuron_vol
rm(up10, upFold, up, down, down10, downFold)
```


# Metascape 
## Neuron
### Format the dataframes
```{r}
i <- "neuron"
# read in enrichment analysis results
up_enrich_results <-
  read_excel(
    paste0(
      "../results/metascape_output/",
      i,
      "_3_vs_0_hours_up_regulated/metascape_result.xlsx"
    ), sheet = 2
  )

down_enrich_results <-
  read_excel(
    paste0(
      "../results/metascape_output/",
      i,
      "_3_vs_0_hours_down_regulated/metascape_result.xlsx"
    ), sheet = 2
  )
```

```{r}
# select the GO term IDs we want to show in the plot
GO_ID_up <-
  c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary",
    "15_Summary",
    "16_Summary",
    "17_Summary",
    "18_Summary",
    "19_Summary", 
    "20_Summary"
  )
GO_ID_down <- c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary", 
    "15_Summary", 
    "16_Summary",
    "17_Summary", 
    "18_Summary", 
    "19_Summary", 
    "20_Summary" 
)

up_enrich_results_subset <-
  up_enrich_results[up_enrich_results$GroupID %in% GO_ID_up, ]
up_enrich_results_subset$Cluster <- c("Upregulated")
up_enrich_results_subset$Description <-
  factor(up_enrich_results_subset$Description,
         levels = up_enrich_results_subset$Description)
up_enrich_results_subset$Description <-
  fct_rev(up_enrich_results_subset$Description)

down_enrich_results_subset <-
  down_enrich_results[down_enrich_results$GroupID %in% GO_ID_down, ]
down_enrich_results_subset$Cluster <- c("Downregulated")
down_enrich_results_subset$Description <-
  factor(down_enrich_results_subset$Description,
         levels = down_enrich_results_subset$Description)
down_enrich_results_subset$Description <-
  fct_rev(down_enrich_results_subset$Description)

# get the number of genes in each summary
up_gene_count <-
  strsplit(as.character(up_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
up_gene_count_df <-
  data.frame(matrix(
    unlist(up_gene_count),
    nrow = length(up_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
up_enrich_results_subset$InTerm <- as.numeric(up_gene_count_df$X1)

down_gene_count <-
  strsplit(as.character(down_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
down_gene_count_df <-
  data.frame(matrix(
    unlist(down_gene_count),
    nrow = length(down_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
down_enrich_results_subset$InTerm <- as.numeric(down_gene_count_df$X1)

# combine together
up_and_down_enrich_results_subset <- rbind(up_enrich_results_subset, down_enrich_results_subset)

up_and_down_enrich_results_subset$Description <-
  factor(up_and_down_enrich_results_subset$Description, levels = unique(up_and_down_enrich_results_subset$Description)) 

up_and_down_enrich_results_subset$Description <-
      gsub(
       "Transport of inorganic cations/anions and amino acids/oligopeptides",
        "Transport inorganic",
        up_and_down_enrich_results_subset$Description
      )

up_and_down_enrich_results_subset$Description <-
      gsub(
       "negative regulation of intracellular signal transduction",
        "neg reg of intracellular signal transductions",
        up_and_down_enrich_results_subset$Description
      )
up_and_down_enrich_results_subset$Description <-
      gsub(
       "negative regulation of phosphate metabolic process",
        "neg reg of phosphate metabolic process",
        up_and_down_enrich_results_subset$Description
      )

up_and_down_enrich_results_subset$Description <-
      gsub(
       "positive regulation of protein targeting to membrane",
        "pos reg of protein targeting to membrane",
        up_and_down_enrich_results_subset$Description
      )

up_and_down_enrich_results_subset$Description <-
      gsub(
       "positive regulation of regulated secretory pathway",
        "pos reg of regulated secretory pathway",
        up_and_down_enrich_results_subset$Description
      )


up_and_down_enrich_results_subset$Description <-
      gsub(
       "Heparan sulfate/heparin (HS-GAG) metabolism",
        "Heparan (HS−GAG) metabolism",
        up_and_down_enrich_results_subset$Description
      )

up_and_down_enrich_results_subset$Description <- fct_rev(up_and_down_enrich_results_subset$Description)
up_and_down_enrich_results_subset$Cluster <- factor(up_and_down_enrich_results_subset$Cluster, levels = c("Upregulated", "Downregulated"))
```

remove files 
```{r}
remove(
  down_enrich_results,
  down_gene_count,
  down_gene_count_df,
  up_enrich_results,
  up_gene_count,
  up_gene_count_df
)
```

### Enrichment plot showing log10 P-value
```{r}
up_and_down_enrich_results_subset$Description <- fct_rev(up_and_down_enrich_results_subset$Description)
# lock in factor level order
up_and_down_enrich_results_subset$Description <- factor(up_and_down_enrich_results_subset$Description, levels =up_and_down_enrich_results_subset$Description)
neuron_up_and_down_enrich_plot <-
  ggplot(data = up_and_down_enrich_results_subset, aes(x = InTerm, y = rev(Description))) +
  #ggplot2::0facet_wrap(~ Cluster, scales = "free_y", ncol = 1) +
 # facet_grid(Cluster ~ ., space="free", scales="free") +
  ggforce::facet_col(facets = vars(Cluster), 
                     scales = "free_y", 
                     space = "free") +
  geom_bar(stat = "identity", aes(fill = LogP), width = .7, position = position_dodge(width = .2)) +
  theme_bw() +
  ggtitle(paste0("")) +
  labs(x = "Gene count", y = NULL) +
  guides(fill = guide_legend(title = expression(log[10] ~ "(" ~ italic("p") ~ "-value)"))) +
  scale_fill_gradientn(
    colours = c("#800026FF","#FD8D3CFF", "#FFFFCCFF"),
    values = scales::rescale(c(-10, -5, -1)), 
    breaks = c(-10, -5, -1), 
    guide = "legend",
    limits = c(-10,-1)
  ) +
    theme(strip.text = element_text(size = 10), 
          axis.text.y = element_text(size = 10),
          axis.text.x = element_text(size = 10), 
          axis.title.x = element_text(size = 10), 
          legend.text = element_text(size = 10),
          legend.title = element_text(size = 10),
          legend.margin=margin(0,0.5,0,0),
          legend.box.margin=margin(-10,-2,-10,-7.5), 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, hjust = -2.85, vjust=0, margin = margin(0,0,0,0)))
 #  theme(aspect.ratio = 1.5) # to reduce the size of the boxes 
addSmallLegend <- function(myPlot, pointSize = 4, textSize = 8, spaceLegend = .5) {
    myPlot +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}

# Apply on original plot
neuron_up_and_down_enrich_plot <- addSmallLegend(neuron_up_and_down_enrich_plot)
neuron_up_and_down_enrich_plot
```

## Interneuron
```{r}
i <- "interneuron"
# read in enrichment analysis results
up_enrich_results <-
  read_excel(
    paste0(
      "../results/metascape_output/",
      i,
      "_3_vs_0_hours_up_regulated/metascape_result.xlsx"
    ), sheet = 2
  )
```

```{r}
# select the GO term IDs we want to show in the plot
GO_ID_up <-
  c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary",
    "15_Summary",
    "16_Summary",
    "17_Summary",
    "18_Summary",
    "19_Summary", 
    "20_Summary"
  )


up_enrich_results_subset <-
  up_enrich_results[up_enrich_results$GroupID %in% GO_ID_up, ]
up_enrich_results_subset$Cluster <- c("Upregulated")
up_enrich_results_subset$Description <-
  factor(up_enrich_results_subset$Description,
         levels = up_enrich_results_subset$Description)
up_enrich_results_subset$Description <-
  fct_rev(up_enrich_results_subset$Description)


# get the number of genes in each summary
up_gene_count <-
  strsplit(as.character(up_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
up_gene_count_df <-
  data.frame(matrix(
    unlist(up_gene_count),
    nrow = length(up_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
up_enrich_results_subset$InTerm <- as.numeric(up_gene_count_df$X1)


# combine together
up_and_down_enrich_results_subset <- rbind(up_enrich_results_subset)

up_and_down_enrich_results_subset$Description <-
  factor(up_and_down_enrich_results_subset$Description, levels = unique(up_and_down_enrich_results_subset$Description)) 

up_and_down_enrich_results_subset$Description <- fct_rev(up_and_down_enrich_results_subset$Description)
up_and_down_enrich_results_subset$Cluster <- factor(up_and_down_enrich_results_subset$Cluster, levels = c("Upregulated", "Downregulated"))
```

remove files 
```{r}
remove(
  down_enrich_results,
  down_gene_count,
  down_gene_count_df,
  up_enrich_results,
  up_gene_count,
  up_gene_count_df
)
```

### Enrichment plot showing log10 P-value
```{r}
up_and_down_enrich_results_subset$Description <- fct_rev(up_and_down_enrich_results_subset$Description)
# lock in factor level order
up_and_down_enrich_results_subset$Description <- factor(up_and_down_enrich_results_subset$Description, levels =up_and_down_enrich_results_subset$Description)
interneuron_up_and_down_enrich_plot <-
  ggplot(data = up_and_down_enrich_results_subset, aes(x = InTerm, y = rev(Description))) +
  #ggplot2::0facet_wrap(~ Cluster, scales = "free_y", ncol = 1) +
 # facet_grid(Cluster ~ ., space="free", scales="free") +
  ggforce::facet_col(facets = vars(Cluster), 
                     scales = "free_y", 
                     space = "free") +
  geom_bar(stat = "identity", aes(fill = LogP), width = .7, position = position_dodge(width = .2)) +
  theme_bw() +
  ggtitle(paste0("")) +
  labs(x = "Gene count", y = NULL) +
  guides(fill = guide_legend(title = expression(log[10] ~ "(" ~ italic("p") ~ "-value)"))) +
  scale_fill_gradientn(
    colours = c("#800026FF","#FD8D3CFF", "#FFFFCCFF"),
    values = scales::rescale(c(-20, -10, -1)), 
    breaks = c(-20, -10, -1), 
    guide = "legend",
    limits = c(-20,-1)
  ) +
    theme(strip.text = element_text(size = 10), 
          axis.text.y = element_text(size = 10),
          axis.text.x = element_text(size = 10), 
          axis.title.x = element_text(size = 10), 
          legend.text = element_text(size = 10),
          legend.title = element_text(size = 10),
          legend.margin=margin(0,0.5,0,0),
          legend.box.margin=margin(-10,-2,-10,-7.5), 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, hjust = -2.85, vjust=0, margin = margin(0,0,0,0)))
 #  theme(aspect.ratio = 1.5) # to reduce the size of the boxes 
addSmallLegend <- function(myPlot, pointSize = 4, textSize = 8, spaceLegend = .5) {
    myPlot +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}

# Apply on original plot
interneuron_up_and_down_enrich_plot <- addSmallLegend(interneuron_up_and_down_enrich_plot)
interneuron_up_and_down_enrich_plot
```


# Combine all plots 
```{r}
row1 <- ggarrange(
  neuron_vol,
  neuron_up_and_down_enrich_plot,
  ncol = 2,
  labels = c("A", "B"), 
  widths = c(1,2),
  font.label = list(size = 10)
)

row2 <- ggarrange(
  interneuron_vol,
  interneuron_up_and_down_enrich_plot,
  ncol = 2,
  labels = c("C", "D"), 
  widths = c(1,2),
  font.label = list(size = 10)
)


combind <-
  ggarrange(
    row1,
    row2,
    nrow = 2,
    heights = c(2, 1)
    )
combind

path <- paste0("../manuscript_figures/Figure_2")
saveToPDF(paste0(path, ".pdf"), width = 7.5, height = 7)
```


