---
title: "Figure 5 - correlation log2FC"
author: "Kimberly Olney, PhD"
date: "08/08/2024"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = ".", echo=TRUE, warning=FALSE, message=FALSE)
library(ComplexHeatmap)
library(ggpubr)
library(dplyr)
```

# Libraris, paths, colors
https://satijalab.org/seurat/articles/essential_commands.html 
```{r echo=FALSE, message=FALSE}
source(here::here("/research/labs/neurology/fryer/m239830/PMI/scripts", "file_paths_and_colours.R"))
treatment <- "PMI"
color.panel <- dittoColors()
metadata <- subset(metadata, sampleID != "P_60" & sampleID != "B_6")
metadata$sampleID <- factor(metadata$sampleID, levels = c(metadata$sampleID))
samples <- metadata$sampleID 
```

# Read in object
```{r read_object}
# read object
dataObject <- readRDS(file = paste0("../rObjects/", treatment, ".dataObject.clean.rds"))
# inspect
dataObject
Layers(dataObject)
# List of cell types to analyze
cell_types <- c(unique(dataObject$individual_clusters))
```

# PS19 vs WT
#### Correlation matrix MAST vs DESeq2
```{r}
DES_deg_list <- list()
for (cell_type in cell_types) {
    DES <- paste0("../results/DEGs/DESeq2_pseudobulk_exp_filter/", cell_type, "_PS19_vs_WT_comparison_pseudobulk.txt")
    DES_deg_data <- read.table(DES, header = TRUE, sep = "\t")
    DES_deg_data <- DES_deg_data %>%
      mutate(cell_type = cell_type)
    DES_deg_list[[paste0(cell_type, "_", "DESeq")]] <- DES_deg_data

}
DES_deg_combined <- bind_rows(DES_deg_list)


MAST_deg_list <- list()
for (cell_type in cell_types) {
    MAST <- paste0("../results/DEGs/MAST/", cell_type, "_PS19_vs_WT_comparison.txt")
    MAST_deg_data <- read.table(MAST, header = TRUE, sep = "\t")
    MAST_deg_data <- MAST_deg_data %>%
      mutate(cell_type = cell_type)
    MAST_deg_list[[paste0(cell_type, "_", "MAST")]] <- MAST_deg_data
}
MAST_deg_combined <- bind_rows(MAST_deg_list)

DEG_combined <- merge(DES_deg_combined, MAST_deg_combined, by = c("gene", "cell_type"), suffixes = c("DESeq", "MAST"))
```

### Plot the data 
```{r}
DEG_combined2 <- na.omit(DEG_combined)

DEG_combined2$cell_type <- factor(DEG_combined2$cell_type, levels = c("neuron", "interneuron", "astrocyte", "oligodendrocyte", "fibroblast", "polydendrocyte", "endothelial", "mural", "microglia"))

ggplot(DEG_combined2, aes(x = log2FoldChange, y = avg_log2FC)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  facet_wrap(~ cell_type, ncol = 3) +
  stat_cor(method = "pearson", label.x = -4, label.y = 4.5) +
  labs(
    title = "Correlation DESeq pseudobulk and MAST log2(PS19/WT) by cell type",
    x = "DESeq log2(PS19/WT)",
    y = "MAST log2(PS19/WT)"
  ) +
  theme_bw() + 
  theme(strip.text = element_text(size = 12))

path <- paste0("../manuscript_figures/Figure_5_genotype_comparison")
saveToPDF(paste0(path, ".pdf"), width = 7.5, height = 7.5)
```


# 3 vs 0 hours
#### Correlation matrix MAST vs DESeq2
```{r}
DES_deg_list <- list()
for (cell_type in cell_types) {
    DES <- paste0("../results/DEGs/DESeq2_pseudobulk_exp_filter/", cell_type, "_3_vs_0_hours_comparison_pseudobulk.txt")
    DES_deg_data <- read.table(DES, header = TRUE, sep = "\t")
    DES_deg_data <- DES_deg_data %>%
      mutate(cell_type = cell_type)
    DES_deg_list[[paste0(cell_type, "_", "DESeq")]] <- DES_deg_data

}
DES_deg_combined <- bind_rows(DES_deg_list)


MAST_deg_list <- list()
for (cell_type in cell_types) {
    MAST <- paste0("../results/DEGs/MAST/", cell_type, "_3_vs_0_hours_comparison.txt")
    MAST_deg_data <- read.table(MAST, header = TRUE, sep = "\t")
    MAST_deg_data <- MAST_deg_data %>%
      mutate(cell_type = cell_type)
    MAST_deg_list[[paste0(cell_type, "_", "MAST")]] <- MAST_deg_data
}
MAST_deg_combined <- bind_rows(MAST_deg_list)

DEG_combined <- merge(DES_deg_combined, MAST_deg_combined, by = c("gene", "cell_type"), suffixes = c("DESeq", "MAST"))
```

### Plot the data 
```{r}
DEG_combined2 <- na.omit(DEG_combined)

DEG_combined2$cell_type <- factor(DEG_combined2$cell_type, levels = c("neuron", "interneuron", "astrocyte", "oligodendrocyte", "fibroblast", "polydendrocyte", "endothelial", "mural", "microglia"))

ggplot(DEG_combined2, aes(x = log2FoldChange, y = avg_log2FC)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  facet_wrap(~ cell_type, ncol = 3) +
  stat_cor(method = "pearson", label.x = -4, label.y = 4.5) +
  labs(
    title = "Correlation DESeq pseudobulk and MAST log2( 3 hour/ 0 hour) by cell type",
    x = "DESeq log2( 3 hour/ 0 hour)",
    y = "MAST log2( 3 hour/ 0 hour)"
  ) +
  theme_bw()  + 
  theme(strip.text = element_text(size = 12))

path <- paste0("../manuscript_figures/Figure_5_time_comparison")
saveToPDF(paste0(path, ".pdf"), width = 7.5, height = 7.5)
```