---
title: "Figure 1 - basic QC"
author: "Kimberly Olney, PhD"
date: "04/19/2024"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = ".", echo=TRUE, warning=FALSE, message=FALSE)
```

# Libraris, paths, colors
https://satijalab.org/seurat/articles/essential_commands.html 
```{r echo=FALSE, message=FALSE}
source(here::here("/research/labs/neurology/fryer/m239830/PMI/scripts", "file_paths_and_colours.R"))
treatment <- "PMI"
group_colors <- c("lightblue", "#bebada", "#377eb8", "#984ea3")
sample_colors <- c("lightblue","lightblue","lightblue","lightblue","#bebada","#bebada","#bebada","#bebada", "#377eb8",  "#377eb8",  "#377eb8",  "#377eb8",  "#377eb8", "#984ea3", "#984ea3", "#984ea3", "#984ea3", "#984ea3")
color.panel <- dittoColors()
library(ggpubr)
```

# Read in object
# Setup seurat object
```{r seurat_object}
prefix <- "../cellranger/"
suffix <- "/outs/filtered_feature_bc_matrix.h5"

samples <- c("P_52", "P_54", "B_9", "J_2", "J_1", "P_64", "P_60", "B_8", "B_7", "P_53", 
                "J_3", "P_65", "P_68", "P_67", "J_4", "B_6", "B_10", "P_62", "P_69", "P_71")

base_path <- "/research/labs/neurology/fryer/m239830/PMI/"

for (i in samples) {
    print(i)
    data_path <- paste0(base_path, "cellrangerMAPT/", i, "/outs/filtered_feature_bc_matrix.h5")
    obj <- CreateSeuratObject(Read10X_h5(data_path))
    assign(i, obj)
  }
  # merge objects
  dataObject <- merge(x = B_7,
                 y = c(P_65, P_69, J_3, J_4, P_52, P_62, P_67, B_10, B_8, B_9, P_71, J_1, J_2, P_53, P_54, P_64, P_68),
                 add.cell.ids = c("B_7", "P_65", "P_69", "J_3", "J_4", "P_52", "P_62", "P_67", "B_10", "B_8",  "B_9",  "P_71", "J_1",  "J_2",  "P_53", "P_54", "P_64" ,"P_68"),
                 project = "PMI")

# Inspect 
dataObject

barcodes <- colnames(dataObject)
sample <- str_match(barcodes, "(.+)_[ACGT]+")[,2]
table(sample)
dataObject$sample <- factor(sample, levels = samples)
table(dataObject$sample)  # check
Idents(dataObject) <- dataObject$sample
DefaultAssay(dataObject) <- "RNA"
Idents(dataObject) <- "seurat_clusters"
dataObject <- NormalizeData(dataObject)
```


# QC violins 
```{r violin}
# nFeature, nCount, and cell.complexity violins
VlnPlot(dataObject,
              features = c("Mapt", "MAPT",  "Xist","Uty"),
              ncol = 2,
              group.by = 'sample',
              cols = sample_colors,
              pt.size = 0.1)  

# Generate individual violin plots
plots <- lapply(c("Mapt", "MAPT",  "Xist","Uty"), function(feature) {
  VlnPlot(dataObject, features = feature, group.by = 'sample', pt.size = 0) + 
    theme(axis.text = element_text(size = 10),
          axis.title = element_text(size = 10),
          axis.title.x = element_blank(),
          plot.title = element_text(size = 10, face = "plain"),
          legend.position = "none") +
    scale_fill_manual(values = sample_colors)

})

# Combine the individual plots into a single plot
v1 <- CombinePlots(plots, ncol = 1, nrow = 4)


Xist <- VlnPlot(dataObject,
              features = c( "Xist"),
              ncol = 1,
              group.by = 'sample',
              cols = sample_colors,
              pt.size = 0)  

Uty <- VlnPlot(dataObject,
              features = c( "Uty"),
              ncol = 1,
              group.by = 'sample',
              cols = sample_colors,
              pt.size = 0)  

Mapt <- VlnPlot(dataObject,
              features = c( "Mapt"),
              ncol = 1,
              group.by = 'sample',
              cols = sample_colors,
              pt.size = 0)  

MAPT <- VlnPlot(dataObject,
              features = c( "MAPT"),
              ncol = 1,
              group.by = 'sample',
              cols = sample_colors,
              pt.size = 0.01)  
```

# Combine all plots 
```{r}

row1 <- ggarrange(
  Xist,
  Uty, 
  Mapt, 
  MAPT,
  ncol = 1,
  nrow = 4,
  labels = c("A", "B", "C", "D"), 
  font.label = list(size = 10)
)

combind <-
  ggarrange(
    v1
    )
combind

path <- paste0("../manuscript_figures/Supplemental_Figure_Sex_check_and_MAPT")
saveToPDF(paste0(path, ".pdf"), width = 7.5, height = 9)
```


