---
title: "Supplemental Figure 6 - 3-hour versus 0-hour differential expression"
author: "Kimberly Olney, PhD"
date: "10/03/2024"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = ".", echo=TRUE, warning=FALSE, message=FALSE)
library("readxl")
library(forcats)
```

# Libraris, paths, colors
https://satijalab.org/seurat/articles/essential_commands.html 
```{r echo=FALSE, message=FALSE}
source(here::here("/research/labs/neurology/fryer/m239830/PMI/scripts", "file_paths_and_colours.R"))
treatment <- "PMI"
```

# Volcano 
```{r params}
qval = 0.1
posFC = 0 
negFC = 0 
FC = 0
```


## endothelial: 3 versus 0 hours
```{r volcano_astroctye, warning=FALSE}
i <- "endothelial"
  ind1_vs_ind2 <- read.delim(paste0("../results/DEGs/DESeq2_pseudobulk_exp_filter/", i, "_3_vs_0_hours_comparison_pseudobulk.txt"))
  ind1_vs_ind2 <- na.omit(ind1_vs_ind2)
sig <- subset(ind1_vs_ind2, padj < 0.1)
up <- subset(sig, log2FoldChange > 0)
down <- subset(sig, log2FoldChange < 0)
    color_values <- vector()
max <- nrow(ind1_vs_ind2)
  for (row in 1:max) {
    if (!is.na(ind1_vs_ind2$padj[row])) {  # Check for NA values in padj
      if (ind1_vs_ind2$padj[row] < qval) {
        if (ind1_vs_ind2$log2FoldChange[row] > posFC) {
          color_values <- c(color_values, 1)
        } else if (ind1_vs_ind2$log2FoldChange[row] < negFC) {
          color_values <- c(color_values, 2)
        } else {
          color_values <- c(color_values, 3)
        }
      } else {
        color_values <- c(color_values, 3)
      }
    } else {
      color_values <- c(color_values, 3)  # Handle NA values in padj
    }
  }
  ind1_vs_ind2$color_adjpval_0.05 <- factor(color_values)
    data <- ind1_vs_ind2
    up <- data[data$color_adjpval_0.05 == 1,]
    up <- up[!grepl("ENSG", up$gene),]
    up10 <- up[1:10,]
    upFold <- subset(up, log2FoldChange > 2)
    upFold <- upFold[!(upFold$gene %in% up10$gene),]
    upFold <- upFold[1:10,]

    down <- data[data$color_adjpval_0.05 == 2,]
    down <- down[!grepl("ENSG", down$gene),]
    down10 <- down[1:10,]
    downFold <- subset(down, log2FoldChange < -2)
    downFold <- downFold[!(downFold$gene %in% down10$gene),]
    downFold <- downFold[1:10,]

    if (!1 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c( "darkgreen","gray")
      } else if (!2 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c("purple","gray")
      } else if (!1 %in% unique(data$color_adjpval_0.05) && !2 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c("gray")
      } else {
        my_colors <- c("purple", "darkgreen","gray")
      }
      # plot
      hadjpval <- (-log10(max(data$pvalue[data$padj < qval], na.rm=TRUE)))

endothelial_vol <- ggplot(data = data, aes(x = log2FoldChange,y = -log10(pvalue), color = color_adjpval_0.05)) + 
        geom_point(alpha = 0.8, size = 1) +  
        theme_bw() +  
        theme(legend.position = "none") + 
        scale_color_manual(values = my_colors) + 
        labs(x = expression(log[2](FC)), 
          y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)") ) +
        theme(legend.position = "none",
              plot.title = element_text(size = 10, margin = margin(0,0,0.3,0)),
              axis.title.x = element_text(size = 10),
              axis.text.x = element_text(size = 10),
              axis.title.y = element_text(size = 10),
              axis.text.y = element_text(size = 10)) +
      geom_hline(yintercept = hadjpval,
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle(paste0(i, "\n3-hour versus 0-hour \nq-value < ", qval)) +
  scale_x_continuous(limits = c(-20, 4), breaks = seq(-20, 4, 4)) +
  scale_y_continuous(limits = c(0, 12), breaks = seq(0, 12, 4))+
      geom_text_repel(
        data = up,
        aes(
          x = log2FoldChange,
          y = -log10(pvalue),
          label = gene
        ),
        nudge_x = 0.1,
        color = "purple",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 8)
      ) +
      geom_text_repel(
        data = down,
        aes(
          x = log2FoldChange,
          y = -log10(pvalue),
          label = gene
        ),
        nudge_x = -0.1,
        color = "darkgreen",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 8)
      ) 
endothelial_vol
rm(up10, upFold, up, down, down10, downFold)
```

## mural: 3 versus 0 hours
```{r volcano_poly, warning=FALSE}
i <- "mural"
  ind1_vs_ind2 <- read.delim(paste0("../results/DEGs/DESeq2_pseudobulk_exp_filter/", i, "_3_vs_0_hours_comparison_pseudobulk.txt"))
  ind1_vs_ind2 <- na.omit(ind1_vs_ind2)

sig <- subset(ind1_vs_ind2, padj < 0.1)
up <- subset(sig, log2FoldChange > 0)
down <- subset(sig, log2FoldChange < 0)

    color_values <- vector()
max <- nrow(ind1_vs_ind2)
  for (row in 1:max) {
    if (!is.na(ind1_vs_ind2$padj[row])) {  # Check for NA values in padj
      if (ind1_vs_ind2$padj[row] < qval) {
        if (ind1_vs_ind2$log2FoldChange[row] > posFC) {
          color_values <- c(color_values, 1)
        } else if (ind1_vs_ind2$log2FoldChange[row] < negFC) {
          color_values <- c(color_values, 2)
        } else {
          color_values <- c(color_values, 3)
        }
      } else {
        color_values <- c(color_values, 3)
      }
    } else {
      color_values <- c(color_values, 3)  # Handle NA values in padj
    }
  }
  ind1_vs_ind2$color_adjpval_0.05 <- factor(color_values)
    data <- ind1_vs_ind2
    up <- data[data$color_adjpval_0.05 == 1,]
    up <- up[!grepl("ENSG", up$gene),]
    up10 <- up[1:10,]
    upFold <- subset(up, log2FoldChange > 2)
    upFold <- upFold[!(upFold$gene %in% up10$gene),]
    upFold <- upFold[1:10,]

    down <- data[data$color_adjpval_0.05 == 2,]
    down <- down[!grepl("ENSG", down$gene),]
    down10 <- down[1:10,]
    downFold <- subset(down, log2FoldChange < -2)
    downFold <- downFold[!(downFold$gene %in% down10$gene),]
    downFold <- downFold[1:10,]

    if (!1 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c( "darkgreen","gray")
      } else if (!2 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c("purple","gray")
      } else if (!1 %in% unique(data$color_adjpval_0.05) && !2 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c("gray")
      } else {
        my_colors <- c("purple", "darkgreen","gray")
      }
      # plot
      hadjpval <- (-log10(max(data$pvalue[data$padj < qval], na.rm=TRUE)))
mural_vol <- ggplot(data = data, aes(x = log2FoldChange,y = -log10(pvalue), color = color_adjpval_0.05)) + 
        geom_point(alpha = 0.8, size = 1) +  
        theme_bw() +  
        theme(legend.position = "none") + 
        scale_color_manual(values = my_colors) + 
        labs(x = expression(log[2](FC)), 
          y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)") ) +
        theme(legend.position = "none",
              plot.title = element_text(size = 10, margin = margin(0,0,0.3,0)),
              axis.title.x = element_text(size = 10),
              axis.text.x = element_text(size = 10),
              axis.title.y = element_text(size = 10),
              axis.text.y = element_text(size = 10)) +
      geom_hline(yintercept = hadjpval,
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle(paste0(i, "\n3-hour versus 0-hour \nq-value < ", qval)) +
  scale_x_continuous(limits = c(-6, 4), breaks = seq(-6, 4, 2)) +
  scale_y_continuous(limits = c(0, 12), breaks = seq(0, 12, 4))+
      geom_text_repel(
        data = up,
        aes(
          x = log2FoldChange,
          y = -log10(pvalue),
          label = gene
        ),
        nudge_x = 0.1,
        color = "purple",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 8)
      ) +
      geom_text_repel(
        data = down,
        aes(
          x = log2FoldChange,
          y = -log10(pvalue),
          label = gene
        ),
        nudge_x = -0.1,
        color = "darkgreen",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 8)
      ) 
mural_vol
rm(up10, upFold, up, down, down10, downFold)
```

## microglia: 3 versus 0 hours
```{r volcano_fibro, warning=FALSE}
i <- "microglia"
  ind1_vs_ind2 <- read.delim(paste0("../results/DEGs/DESeq2_pseudobulk_exp_filter/", i, "_3_vs_0_hours_comparison_pseudobulk.txt"))
  ind1_vs_ind2 <- na.omit(ind1_vs_ind2)
sig <- subset(ind1_vs_ind2, padj < 0.1)
up <- subset(sig, log2FoldChange > 0)
down <- subset(sig, log2FoldChange < 0)
    color_values <- vector()
max <- nrow(ind1_vs_ind2)
  for (row in 1:max) {
    if (!is.na(ind1_vs_ind2$padj[row])) {  # Check for NA values in padj
      if (ind1_vs_ind2$padj[row] < qval) {
        if (ind1_vs_ind2$log2FoldChange[row] > posFC) {
          color_values <- c(color_values, 1)
        } else if (ind1_vs_ind2$log2FoldChange[row] < negFC) {
          color_values <- c(color_values, 2)
        } else {
          color_values <- c(color_values, 3)
        }
      } else {
        color_values <- c(color_values, 3)
      }
    } else {
      color_values <- c(color_values, 3)  # Handle NA values in padj
    }
  }
  ind1_vs_ind2$color_adjpval_0.05 <- factor(color_values)
    data <- ind1_vs_ind2
    up <- data[data$color_adjpval_0.05 == 1,]
    up <- up[!grepl("ENSG", up$gene),]
    up10 <- up[1:10,]
    upFold <- subset(up, log2FoldChange > 2)
    upFold <- upFold[!(upFold$gene %in% up10$gene),]
    upFold <- upFold[1:10,]

    down <- data[data$color_adjpval_0.05 == 2,]
    down <- down[!grepl("ENSG", down$gene),]
    down10 <- down[1:10,]
    downFold <- subset(down, log2FoldChange < -2)
    downFold <- downFold[!(downFold$gene %in% down10$gene),]
    downFold <- downFold[1:10,]

    if (!1 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c( "darkgreen","gray")
      } else if (!2 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c("purple","gray")
      } else if (!1 %in% unique(data$color_adjpval_0.05) && !2 %in% unique(data$color_adjpval_0.05)) {
        my_colors <- c("gray")
      } else {
        my_colors <- c("purple", "darkgreen","gray")
      }
      # plot
      hadjpval <- (-log10(max(data$pvalue[data$padj < qval], na.rm=TRUE)))

microglia_vol <- ggplot(data = data, aes(x = log2FoldChange,y = -log10(pvalue), color = color_adjpval_0.05)) + 
        geom_point(alpha = 0.8, size = 1) +  
        theme_bw() +  
        theme(legend.position = "none") + 
        scale_color_manual(values = "gray") + 
        labs(x = expression(log[2](FC)), 
          y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)") ) +
        theme(legend.position = "none",
              plot.title = element_text(size = 10, margin = margin(0,0,0.3,0)),
              axis.title.x = element_text(size = 10),
              axis.text.x = element_text(size = 10),
              axis.title.y = element_text(size = 10),
              axis.text.y = element_text(size = 10)) +
      geom_hline(yintercept = hadjpval,
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle(paste0(i, "\n3-hour versus 0-hour \nq-value < ", qval)) +
  scale_x_continuous(limits = c(-6, 4), breaks = seq(-6, 4, 2)) +
  scale_y_continuous(limits = c(0, 12), breaks = seq(0, 12, 4))+
      geom_text_repel(
        data = up,
        aes(
          x = log2FoldChange,
          y = -log10(pvalue),
          label = gene
        ),
        nudge_x = 0.1,
        color = "purple",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 8)
      ) +
      geom_text_repel(
        data = down,
        aes(
          x = log2FoldChange,
          y = -log10(pvalue),
          label = gene
        ),
        nudge_x = -0.1,
        color = "darkgreen",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 8)
      ) 
microglia_vol
rm(up10, upFold, up, down, down10, downFold)
```

# Combine all plots 
```{r}

row1 <- ggarrange(
  endothelial_vol,
  mural_vol,
  ncol = 2,
  labels = c("A", "B"), 
  font.label = list(size = 10)
)

row2 <- ggarrange(
  microglia_vol,
  ncol = 2,
  labels = c("C", ""), 
  font.label = list(size = 10)
)


combind <-
  ggarrange(
    row1,
    row2,
    nrow = 2
    )
combind

path <- paste0("../manuscript_figures/Supplemental_Fig_6")
saveToPDF(paste0(path, ".pdf"), width = 7.5, height = 5.5)
```

```{r}
```

